name: rich_pich_2
description: "A new Flutter project."

# publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  iconable_avatar: 0.0.4
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  font_awesome_flutter: ^10.0.0
  firebase_core: ^3.4.1
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.2.1
  firebase_storage: ^12.3.0


  

  cupertino_icons: ^1.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  mockito: ^5.4.0 
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
